// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CustomerRequest struct {
	Id                   int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*CustomerRequest_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CustomerRequest) Reset()         { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()    {}
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_65280272e36dead3, []int{0}
}
func (m *CustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest.Unmarshal(m, b)
}
func (m *CustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest.Marshal(b, m, deterministic)
}
func (dst *CustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest.Merge(dst, src)
}
func (m *CustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest.Size(m)
}
func (m *CustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest proto.InternalMessageInfo

func (m *CustomerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRequest) GetAddresses() []*CustomerRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerRequest_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerRequest_Address) Reset()         { *m = CustomerRequest_Address{} }
func (m *CustomerRequest_Address) String() string { return proto.CompactTextString(m) }
func (*CustomerRequest_Address) ProtoMessage()    {}
func (*CustomerRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_65280272e36dead3, []int{0, 0}
}
func (m *CustomerRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequest_Address.Unmarshal(m, b)
}
func (m *CustomerRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequest_Address.Marshal(b, m, deterministic)
}
func (dst *CustomerRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequest_Address.Merge(dst, src)
}
func (m *CustomerRequest_Address) XXX_Size() int {
	return xxx_messageInfo_CustomerRequest_Address.Size(m)
}
func (m *CustomerRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequest_Address proto.InternalMessageInfo

func (m *CustomerRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *CustomerRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type CustomerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerResponse) Reset()         { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()    {}
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_65280272e36dead3, []int{1}
}
func (m *CustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerResponse.Unmarshal(m, b)
}
func (m *CustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerResponse.Marshal(b, m, deterministic)
}
func (dst *CustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerResponse.Merge(dst, src)
}
func (m *CustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerResponse.Size(m)
}
func (m *CustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerResponse proto.InternalMessageInfo

func (m *CustomerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CustomerFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerFilter) Reset()         { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string { return proto.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()    {}
func (*CustomerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_65280272e36dead3, []int{2}
}
func (m *CustomerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerFilter.Unmarshal(m, b)
}
func (m *CustomerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerFilter.Marshal(b, m, deterministic)
}
func (dst *CustomerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerFilter.Merge(dst, src)
}
func (m *CustomerFilter) XXX_Size() int {
	return xxx_messageInfo_CustomerFilter.Size(m)
}
func (m *CustomerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerFilter proto.InternalMessageInfo

func (m *CustomerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerRequest)(nil), "customer.CustomerRequest")
	proto.RegisterType((*CustomerRequest_Address)(nil), "customer.CustomerRequest.Address")
	proto.RegisterType((*CustomerResponse)(nil), "customer.CustomerResponse")
	proto.RegisterType((*CustomerFilter)(nil), "customer.CustomerFilter")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_customer_65280272e36dead3) }

var fileDescriptor_customer_65280272e36dead3 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x5d, 0x4a, 0xc3, 0x40,
	0x10, 0x80, 0xbb, 0x69, 0xd3, 0x9f, 0x51, 0x62, 0x1d, 0x44, 0xd6, 0x3c, 0xc5, 0x3c, 0x05, 0x91,
	0x22, 0xf5, 0x55, 0x10, 0x29, 0x58, 0x7c, 0x8d, 0x27, 0x88, 0xc9, 0x60, 0x17, 0xdb, 0x24, 0xee,
	0x6e, 0x91, 0x7a, 0x05, 0xef, 0xe0, 0x19, 0x3c, 0xa2, 0xec, 0x26, 0xdb, 0x82, 0xb5, 0x6f, 0xf3,
	0xcd, 0xec, 0xcc, 0x7e, 0x3b, 0x09, 0x04, 0xf9, 0x5a, 0xe9, 0x6a, 0x45, 0x72, 0x52, 0xcb, 0x4a,
	0x57, 0x38, 0x74, 0x1c, 0xff, 0x78, 0x70, 0x32, 0x6b, 0x21, 0xa5, 0xf7, 0x35, 0x29, 0x8d, 0x01,
	0x78, 0xa2, 0xe0, 0x2c, 0x62, 0x89, 0x9f, 0x7a, 0xa2, 0x40, 0x84, 0x5e, 0x99, 0xad, 0x88, 0x7b,
	0x11, 0x4b, 0x46, 0xa9, 0x8d, 0xf1, 0x0c, 0x7c, 0x5a, 0x65, 0x62, 0xc9, 0xbb, 0x36, 0xd9, 0x80,
	0xc9, 0xd6, 0x8b, 0xaa, 0x24, 0xde, 0x6b, 0xb2, 0x16, 0xf0, 0x1e, 0x46, 0x59, 0x51, 0x48, 0x52,
	0x8a, 0x14, 0xf7, 0xa3, 0x6e, 0x72, 0x34, 0xbd, 0x9c, 0x6c, 0x8d, 0xfe, 0xdc, 0x3e, 0x79, 0x68,
	0x8e, 0xa6, 0xbb, 0x9e, 0xf0, 0x8b, 0xc1, 0xa0, 0x4d, 0xe3, 0x39, 0xf4, 0x95, 0x96, 0x44, 0xda,
	0x0a, 0x8e, 0xd2, 0x96, 0x8c, 0x64, 0x2e, 0xf4, 0xc6, 0x49, 0x9a, 0xd8, 0xe8, 0x28, 0x9d, 0x69,
	0x72, 0x92, 0x16, 0x70, 0x0c, 0xdd, 0x4f, 0x51, 0xb7, 0x8a, 0x26, 0xc4, 0x6b, 0x38, 0x15, 0xea,
	0x79, 0x21, 0xea, 0x5a, 0x94, 0xaf, 0xed, 0x45, 0xdc, 0x8f, 0x58, 0x32, 0x4c, 0xf7, 0x0b, 0xf1,
	0x1d, 0x8c, 0x77, 0xce, 0xaa, 0xae, 0x4a, 0x45, 0x7b, 0x2b, 0xe3, 0x30, 0x50, 0xeb, 0x3c, 0x37,
	0x73, 0x3c, 0x3b, 0xc7, 0x61, 0x7c, 0x05, 0x81, 0xeb, 0x7e, 0x14, 0x4b, 0x4d, 0xd2, 0x9c, 0x7d,
	0xa3, 0xcd, 0x47, 0x25, 0x8b, 0xf6, 0x49, 0x0e, 0xa7, 0xdf, 0x0c, 0xb6, 0x5f, 0x0a, 0xe7, 0x70,
	0x3c, 0x27, 0xed, 0x50, 0x21, 0xdf, 0x5f, 0x61, 0x33, 0x30, 0xbc, 0x38, 0xb8, 0xdc, 0xb8, 0x73,
	0xc3, 0xf0, 0x09, 0x82, 0x99, 0xa4, 0x4c, 0x93, 0x2b, 0xe2, 0xe1, 0x86, 0x30, 0xfc, 0xaf, 0xd4,
	0x3c, 0x3a, 0xee, 0xbc, 0xf4, 0xed, 0xef, 0x74, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x8b,
	0x1b, 0x9e, 0x60, 0x02, 0x00, 0x00,
}
